### ISSUE TITLE
Internal KeyError: 'access_token'

### ISSUE THREAD

**Issue by BeeMoe5** [supertokens/supertokens-python#202]
Traceback:
```py
Traceback (most recent call last):
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\uvicorn\middleware\debug.py", line 106, in __call__
    raise exc from None
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\uvicorn\middleware\debug.py", line 103, in __call__
    await self.app(scope, receive, inner_send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\fastapi\applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\starlette\middleware\base.py", line 68, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\framework\fastapi\fastapi_middleware.py", line 49, in dispatch
    result: Union[BaseResponse, None] = await st.middleware(custom_request, response)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\supertokens.py", line 402, in middleware
    api_resp = await matched_recipe.handle_api_request(request_id, request, path, method, response)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdpartyemailpassword\recipe.py", line 215, in handle_api_request
    return await self.third_party_recipe.handle_api_request(request_id, request, path, method, response)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdparty\recipe.py", line 110, in handle_api_request
    return await handle_sign_in_up_api(self.api_implementation,
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdparty\api\signinup.py", line 66, in handle_sign_in_up_api
    result = await api_implementation.sign_in_up_post(provider, code, body['redirectURI'], client_id,
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdpartyemailpassword\api\thirdparty_api_implementation.py", line 40, in sign_in_up_post
    result = await api_implementation.thirdparty_sign_in_up_post(provider, code, redirect_uri, client_id, auth_code_response, api_options, user_context)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdpartyemailpassword\api\implementation.py", line 88, in thirdparty_sign_in_up_post
    result = await self.tp_sign_in_up_post(provider, code, redirect_uri, client_id, auth_code_response, api_options, user_context)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdparty\api\implementation.py", line 120, in sign_in_up_post
    user_info: UserInfo = await provider.get_profile_info(access_token_response, user_context)
  File "C:\Users\cassa\AppData\Local\pypoetry\Cache\virtualenvs\game-9Q8vL6rk-py3.8\lib\site-packages\supertokens_python\recipe\thirdparty\providers\discord.py", line 47, in get_profile_info
    access_token: str = auth_code_response['access_token']
KeyError: 'access_token'
```
i am using fastapi, my middleware setup is
```py
app.add_middleware(get_middleware())
supertokens_python.init(
    supertokens_config=supertokens_python.SupertokensConfig(
        connection_uri=ST_CONNECTION_URI, api_key=ST_API_KEY
    ),
    app_info=supertokens_python.InputAppInfo(
        app_name="game",
        api_domain="http://localhost:9000",
        website_domain="http://localhost:3000",
        api_base_path="/api",
        website_base_path="/",
    ),
    framework="fastapi",
    recipe_list=[
        session.init(),
        thirdpartyemailpassword.init(
            providers=[
                Discord(
                    client_id=DISCORD_CLIENT_ID, client_secret=DISCORD_CLIENT_SECRET
                )
            ]
        ),
    ],
    telemetry=False,
)
```

**Comment by KShivendu** [comment]
Hey @BeeMoe5, 

Could you please recheck the credentials (esp. `client_secret`) 

`access_token` related errors are expected to appear if the credentials are wrong.

**Comment by BeeMoe5** [comment]
@KShivendu okay, that was the issue. discord made getting the client secret hard without resetting it, so i took an invalid one from a previous project file thinking it was valid. thank you

**Comment by rishabhpoddar** [comment]
Thank you @KShivendu. I am closing this PR. Please feel free to reopen in case the error persists
