### ISSUE TITLE
Werkzeug dependency failing when running Flask application

### ISSUE THREAD

**Issue by OyugoObonyo** [supertokens/supertokens-python#277]
When attempting to run my flask application after installing the supertokens-python package, I'm hit with the following error:

```
TypeError: LocalProxy.__init__() got an unexpected keyword argument 'unbound_message'
```
The full stack trace is as follows:
```
Traceback (most recent call last):
  File "/media/xbyugo/BRUNO MEDIA/CODE/PLAY/Flask_Auth/main.py", line 1, in <module>
    from app import create_app
  File "/media/xbyugo/BRUNO MEDIA/CODE/PLAY/Flask_Auth/app/__init__.py", line 2, in <module>
    from flask import Flask
  File "/media/xbyugo/BRUNO MEDIA/CODE/PLAY/Flask_Auth/.venv/lib/python3.10/site-packages/flask/__init__.py", line 4, in <module>
    from . import json as json
  File "/media/xbyugo/BRUNO MEDIA/CODE/PLAY/Flask_Auth/.venv/lib/python3.10/site-packages/flask/json/__init__.py", line 8, in <module>
    from ..globals import current_app
  File "/media/xbyugo/BRUNO MEDIA/CODE/PLAY/Flask_Auth/.venv/lib/python3.10/site-packages/flask/globals.py", line 56, in <module>
    app_ctx: "AppContext" = LocalProxy(  # type: ignore[assignment]
TypeError: LocalProxy.__init__() got an unexpected keyword argument 'unbound_message'
```
Upon investigation, I figured that the error is caused by a dependency fault. supertokens-python v0.11.13 requires werkzeug of any version between 2.0 and 2.1.0. However, Flask 2.2.2(which is the latest stable version of flask) requires werkzeug v2.2.2. Downgrading Werkzeug to accomodate supertokens-python renders flask unusable while upgrading werkzeug to v2.2.2 renders supertokens-python unusable. Please look into this matter.

**Comment by rishabhpoddar** [comment]
This has been fixed in version >= 0.12.0
