### ISSUE TITLE
tldextract library isn't handling ec2-xx-yyy-zzz-0.compute-1.amazonaws.com

### ISSUE THREAD

**Issue by byrleyar** [supertokens/supertokens-python#394]
Setting api_domain to `http:\\ec2-xx-yyy-zzz-0.compute-1.amazonaws.com` causes this error:

```
Traceback (most recent call last):
  ...
  File "/home/andrew/PycharmProjects/reminderFastApi/venv/lib/python3.10/site-packages/supertokens_python/__init__.py", line 35, in init
    return Supertokens.init(
  File "/home/andrew/PycharmProjects/reminderFastApi/venv/lib/python3.10/site-packages/supertokens_python/supertokens.py", line 209, in init
    Supertokens.__instance = Supertokens(
  File "/home/andrew/PycharmProjects/reminderFastApi/venv/lib/python3.10/site-packages/supertokens_python/supertokens.py", line 157, in __init__
    self.app_info = AppInfo(
  File "/home/andrew/PycharmProjects/reminderFastApi/venv/lib/python3.10/site-packages/supertokens_python/supertokens.py", line 108, in __init__
    self.top_level_api_domain = get_top_level_domain_for_same_site_resolution(
  File "/home/andrew/PycharmProjects/reminderFastApi/venv/lib/python3.10/site-packages/supertokens_python/utils.py", line 279, in get_top_level_domain_for_same_site_resolution
    raise Exception(
Exception: Please make sure that the apiDomain and websiteDomain have correct values
```

This is in supertokens-python version 0.12.9

**Comment by rishabhpoddar** [comment]
This has been fixed in python sdk version >= 0.16.1
