### ISSUE TITLE
consume_code_post() takes 6 positional arguments but 7 were given

### ISSUE THREAD

**Issue by TNick** [supertokens/supertokens-python#495]
For some reason with the latest version throws an error at this line.

https://github.com/supertokens/supertokens-python/blob/e1650b8765c0118981dfc6821d050c1a531b872a/supertokens_python/recipe/passwordless/api/consume_code.py#L59

```
Traceback (most recent call last):
  File "xxx\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "xxx\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "xxx\venv\lib\site-packages\uvicorn\middleware\message_logger.py", line 84, in __call__
    raise exc from None
  File "xxx\venv\lib\site-packages\uvicorn\middleware\message_logger.py", line 80, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "xxx\webapp\app_class.py", line 63, in __call__
    await super().__call__(scope, receive, send)
  File "xxx\venv\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "xxx\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "xxx\venv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "xxx\venv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "xxx\venv\lib\site-packages\supertokens_python\framework\fastapi\fastapi_middleware.py", line 49, in dispatch
    result: Union[BaseResponse, None] = await st.middleware(
  File "xxx\venv\lib\site-packages\supertokens_python\supertokens.py", line 638, in middleware
    api_resp = await matched_recipe.handle_api_request(
  File "xxx\venv\lib\site-packages\supertokens_python\recipe\passwordless\recipe.py", line 206, in handle_api_request
    return await consume_code(
  File "xxx\venv\lib\site-packages\supertokens_python\recipe\passwordless\api\consume_code.py", line 59, in consume_code
    result = await api_implementation.consume_code_post(
TypeError: consume_code_post() takes 6 positional arguments but 7 were given
```

When invoking the function using named arguments the error is:
```

Traceback (most recent call last):
  File "xxx\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "xxx\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "xxx\venv\lib\site-packages\uvicorn\middleware\message_logger.py", line 84, in __call__
    raise exc from None
  File "xxx\venv\lib\site-packages\uvicorn\middleware\message_logger.py", line 80, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "xxx\webapp\app_class.py", line 63, in __call__
    await super().__call__(scope, receive, send)
  File "xxx\venv\lib\site-packages\fastapi\applications.py", line 289, in __call__
    await super().__call__(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "xxx\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "xxx\venv\lib\site-packages\starlette\middleware\cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "xxx\venv\lib\site-packages\starlette\middleware\cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "xxx\venv\lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "xxx\venv\lib\site-packages\supertokens_python\framework\fastapi\fastapi_middleware.py", line 49, in dispatch
    result: Union[BaseResponse, None] = await st.middleware(
  File "xxx\venv\lib\site-packages\supertokens_python\supertokens.py", line 638, in middleware
    api_resp = await matched_recipe.handle_api_request(
  File "xxx\venv\lib\site-packages\supertokens_python\recipe\passwordless\recipe.py", line 206, in handle_api_request
    return await consume_code(
  File "xxx\venv\lib\site-packages\supertokens_python\recipe\passwordless\api\consume_code.py", line 59, in consume_code
    result = await api_implementation.consume_code_post(
TypeError: consume_code_post() got an unexpected keyword argument 'tenant_id'
```
To conclude this weirdness the `api_implementation.consume_code_post` in debugger indicates that it is `function override_passwordless_apis.<locals>.consume_code_post` but I cannot find any `override_passwordless_apis` except in tests.

**Comment by TNick** [comment]
Version `0.14.8` seems to be the last version that I can use. It makes sense as the tenant was added with version `0.15.0`.

**Comment by rishabhpoddar** [comment]
Does this happen when you call the consume code POST API from the frontend? If so, can i see the request body?

**Comment by TNick** [comment]
Sorry about the false report. One of the libraries that I'm using does this 
```
  override=passwordless.InputOverrideConfig(
      apis=override_passwordless_apis
  ),
```
The problem is there, not with `supertokens-python`.
