### ISSUE TITLE
tldts library isn't handling azure URLs: https://[appName]-[appId].[region]-01.azurewebsites.net

### ISSUE THREAD

**Issue by vshia** [supertokens/supertokens-python#550]
Setting api_domain to `https://[appName]-[appId].[region]-01.azurewebsites.net` causes this error:

```
Error: Please make sure that the apiDomain and websiteDomain have correct values
    at getTopLevelDomainForSameSiteResolution (/home/node/app/node_modules/supertokens-node/lib/build/utils.js:351:15)
    at Object.normaliseInputAppInfoOrThrowError (/home/node/app/node_modules/supertokens-node/lib/build/utils.js:121:31)
    at new SuperTokens (/home/node/app/node_modules/supertokens-node/lib/build/supertokens.js:348:32)
    at SuperTokensWrapper.init (/home/node/app/node_modules/supertokens-node/lib/build/supertokens.js:440:36)
    at Object.<anonymous> (/home/node/app/api/dist/functions/auth.js:38:33)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at cjsLoader (node:internal/modules/esm/translators:346:17)
```

This is with supertokens-node version 15.2.3

I imagine the fix is similar to https://github.com/supertokens/supertokens-python/issues/394

**Comment by vshia** [comment]
Sorry, will repost in the proper repo
