### ISSUE TITLE
RuntimeWarning: coroutine was never awaited

### ISSUE THREAD

**Issue by lukehassel** [supertokens/supertokens-python#94]
I am getting this error after executing the sample code below:

```python
/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/supertokens_python/recipe/session/recipe_implementation.py:81: RuntimeWarning: coroutine 'RecipeImplementation.__init__.<locals>.call_get_handshake_info' was never awaited
  pass
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
INFO:     Started server process [9584]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not str
Call stack:
  File "/Users/luke/PycharmProjects/supertoken/main.py", line 109, in <module>
    uvicorn.run(app, host="0.0.0.0", port=get_api_port())  # type: ignore
  File "/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/uvicorn/main.py", line 452, in run
    server.run()
  File "/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/uvicorn/server.py", line 86, in serve
    await self.startup(sockets=sockets)
  File "/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/uvicorn/server.py", line 176, in startup
    self._log_started_message(listeners)
  File "/Users/luke/PycharmProjects/supertoken/venv1/lib/python3.10/site-packages/uvicorn/server.py", line 217, in _log_started_message
    logger.info(
Message: 'Uvicorn running on %s://%s:%d (Press CTRL+C to quit)'
Arguments: ('http', '0.0.0.0', '3001')
```

```python
import os
import typing
from typing import Union

import uvicorn  # type: ignore
from dotenv import load_dotenv
from fastapi import Depends, FastAPI, Response
from fastapi.responses import JSONResponse, PlainTextResponse
from starlette.datastructures import Headers
from starlette.exceptions import ExceptionMiddleware
from starlette.middleware.cors import CORSMiddleware
from starlette.types import ASGIApp
from supertokens_python import (InputAppInfo, SupertokensConfig,
                                get_all_cors_headers, init)
from supertokens_python.framework.fastapi import Middleware
from supertokens_python.recipe import session, thirdpartyemailpassword
from supertokens_python.recipe.session import SessionContainer
from supertokens_python.recipe.session.framework.fastapi import verify_session
from supertokens_python.recipe.thirdpartyemailpassword import (
    Apple, Discord, Github, Google, GoogleWorkspaces)

load_dotenv()

app = FastAPI(debug=True)
app.add_middleware(Middleware)
os.environ.setdefault('SUPERTOKENS_ENV', 'testing')


def get_api_port():
    return '3001'


def get_website_port():
    return '3000'


def get_website_domain():
    return 'http://localhost:' + get_website_port()


init(
    supertokens_config=SupertokensConfig(
        connection_uri='https://try.supertokens.io'
    ),
    app_info=InputAppInfo(
        app_name='Supertokens',
        api_domain='0.0.0.0' + get_api_port(),
        website_domain=get_website_domain()
    ),
    framework='fastapi',
    recipe_list=[
        session.init(),
    ],
    telemetry=False
)

app.add_middleware(ExceptionMiddleware, handlers=app.exception_handlers)


@app.get('/sessioninfo')
async def get_session_info(session_: SessionContainer = Depends(verify_session())):
    return JSONResponse({
        'sessionHandle': session_.get_handle(),
        'userId': session_.get_user_id(),
        'accessTokenPayload': session_.get_access_token_payload(),
        # 'sessionData': await session_.get_session_data()
    })


@app.exception_handler(405)  # type: ignore
def f_405(_, __: Exception):
    return PlainTextResponse('', status_code=404)


class CustomCORSMiddleware(CORSMiddleware):
    def __init__(
            self,
            app_: ASGIApp,
            allow_origins: typing.Sequence[str] = (),
            allow_methods: typing.Sequence[str] = ("GET",),
            allow_headers: typing.Sequence[str] = (),
            allow_credentials: bool = False,
            allow_origin_regex: Union[str, None] = None,
            expose_headers: typing.Sequence[str] = (),
            max_age: int = 600,
    ) -> None:
        super().__init__(app_, allow_origins, allow_methods, allow_headers, allow_credentials, allow_origin_regex, expose_headers, max_age)  # type: ignore

    def preflight_response(self, request_headers: Headers) -> Response:
        result: Response = super().preflight_response(request_headers)
        if result.status_code == 200:  # type: ignore
            result.headers.__delitem__('content-type')
            result.headers.__delitem__('content-length')
            return Response(status_code=204, headers=dict(result.headers))
        return result


app = CustomCORSMiddleware(  # type: ignore
    app_=app,
    allow_origins=[
        get_website_domain()
    ],
    allow_credentials=True,
    allow_methods=["GET", "PUT", "POST", "DELETE", "OPTIONS", "PATCH"],
    allow_headers=["Content-Type"] + get_all_cors_headers(),
)

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=get_api_port())  # type: ignore```

**Comment by rishabhpoddar** [comment]
How are you running the app? The readme says you should run it like:
```
uvicorn main:app --reload --host=0.0.0.0 --port=3001
```

I just tried it, and the command above works:
```
> uvicorn main:app --reload --host=0.0.0.0 --port=3001
INFO:     Uvicorn running on http://0.0.0.0:3001 (Press CTRL+C to quit)
INFO:     Started reloader process [73789] using statreload
INFO:     Started server process [73792]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

**Comment by lukehassel** [comment]
It's now working. Thanks.
